CREATE TABLE BG_USER (U_ID INTEGER, U_NAME TEXT, U_PASS TEXT, U_ACTIVE BOOL);
CREATE TABLE BG_INCIDENT (I_ID INT, I_SUBJECT TEXT, I_DESC TEXT, I_CDATE TEXT, I_UDATE TEXT, I_ACTIVE TEXT, I_STATUS TEXT, I_U_ID INT);
CREATE TABLE BG_I_HIST (H_I_ID INT, H_U_ID INT, H_COMMENT TEXT, H_STATUS TEXT, H_UPDATE TEXT);
